### ISSUE TITLE
Run specific jobs in the glue-workflow.

### ISSUE THREAD

**Issue by Rachapalli94** [awsdocs/aws-glue-developer-guide#100]
Issue 1: How to start aws glue workflow from a specific **intermittent step** and run to **end**?

Issue 2: in the **start_workflow_run()** can we use any  **aruguments** to run the **specific glue job** through workflow or any other approach we need to follow?

@kkadiyam

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
