### ISSUE TITLE
Python wheel for glue spark job invalid

### ISSUE THREAD

**Issue by StevenTollanis** [awsdocs/aws-glue-developer-guide#101]
Hi,

I'm trying to build a wheel for using it in a glue spark job. Already built it locally and even ran it, but when I added it to the glue job using **--additional-python-modules** and run the job.  Logs say "**Wheel 'name' located at /tmp/name-0.0.1-py3-none-any.whl is invalid**" Finally glue shows **LAUNCH ERROR | Python Module Installer indicates modules that failed to install, check logs from the PythonModuleInstaller.Please refer logs for details.**

Link followed: [https://docs.aws.amazon.com/glue/latest/dg/aws-glue-programming-python-libraries.html#addl-python-modules-support](https://docs.aws.amazon.com/glue/latest/dg/aws-glue-programming-python-libraries.html#addl-python-modules-support)

Thanks for any hint.

**Comment by quixoticmonk** [comment]
Is the whl file in a target s3 bucket and the `--additional-python-modules` is set to that path ?

**Comment by StevenTollanis** [comment]
> Is the whl file in a target s3 bucket and the `--additional-python-modules` is set to that path ?

Yes

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
