### ISSUE TITLE
always try to load data from mysql.user if 'dbtable'='user'

### ISSUE THREAD

**Issue by Char1ei** [awsdocs/aws-glue-developer-guide#104]
Hi there,

There is a MYSQL table called `user` in our database xxx, and we are trying to load data via Glue job.
Glue job can't load data correctly from xxx.user, looks like it always try to load data from `mysql.user` and I got this error.

`An error occurred while calling o86.getDynamicFrame. Unknown column 'Host' in 'field list'`

it was working last week.

e.g.
`
glueContext.create_dynamic_frame.from_options(
  connection_type="mysql",
  connection_options={
  "useConnectionProperties": "true",
  "dbtable": "user",
  "connectionName": "some_predined_glue_connection"
  }
)
`

 got the same error even I have schema. `"dbtable": "xxx.user",`

**Comment by Char1ei** [comment]
A workaround I found is limiting the permission of the user for glue connection. it can point to correctly `user` table if the user can't access to the schema `msyql`.

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
