### ISSUE TITLE
How can we access Athena views from AWS Glue?

### ISSUE THREAD

**Issue by hastimal** [awsdocs/aws-glue-developer-guide#14]
I am trying to access Athena views from Glue, not sure if we can do that either.

**Comment by janetst** [comment]
@hastimal , you can create a table in the Glue Data Catalog that access the Athena view through JDBC. See https://docs.aws.amazon.com/athena/latest/ug/views.html#considerations-views and also https://docs.aws.amazon.com/athena/latest/ug/glue-best-practices.html. 

I hope this answers your question, and I sincerely apologize for the lateness of this response.
