### ISSUE TITLE
PyGlue.zip is outdated

### ISSUE THREAD

**Issue by dmytro-bekuzarov** [awsdocs/aws-glue-developer-guide#28]
PyGlue.zip located here:
https://s3.amazonaws.com/aws-glue-jes-prod-us-east-1-assets/etl/python/PyGlue.zip
is outdated and does not include the latest changes in the Glue service, such as logger: `glueContext.get_logger()`
Please, update to the latest version

**Comment by rubyumeshc** [comment]
Greetings dmytro-bekuzarov, 

Seems like this repo is not actively maintained, could you please submit the feedback from the AWS public docs using "submit feedback" also if possible create a case with AWS support to get faster response.

**Comment by dmytro-bekuzarov** [comment]
Closing this issues since Amazon recently release official libraries:
https://aws.amazon.com/about-aws/whats-new/2019/08/aws-glue-releases-binaries-of-glue-etl-libraries-for-glue-jobs/
