### ISSUE TITLE
Warning about `ApplyMapping` source type mismatch

### ISSUE THREAD

**Issue by rofinn** [awsdocs/aws-glue-developer-guide#3]
If the source type doesn't match the dataset then an empty column will silently be created rather than attempting to convert or throw an error. The [ApplyMapping](https://github.com/awsdocs/aws-glue-developer-guide/blob/master/doc_source/aws-glue-api-crawler-pyspark-transforms-ApplyMapping.md) documentation should probably include a warning about this behaviour.

**Comment by janetst** [comment]
@rofinn , yes, that does sound like useful information to add to the docs. I will create a ticket to investigate and possibly implement this addition to the docs.

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the "awsdocs" org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
