### ISSUE TITLE
Retention parameter

### ISSUE THREAD

**Issue by vatshat** [awsdocs/aws-glue-developer-guide#34]
Hi, 

Can we please provide better clarification regarding the unit of time for the "Retention" parameter. Unit should be "day". 

https://docs.aws.amazon.com/glue/latest/dg/aws-glue-api-catalog-tables.html

**Comment by janetst** [comment]
HI @vatshat  - I will open a ticket to get this fixed. I agree, this needs to be stated more clearly.

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the "awsdocs" org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
