### ISSUE TITLE
Local Jupiter, connected to Glue Developer Endpoint

### ISSUE THREAD

**Issue by Smotrov** [awsdocs/aws-glue-developer-guide#36]
Dear colleagues, 
I believe, it would be good to have documentation about how to connect locally installed Jupiter (Lab) with Developer Endpoint. Because Zeppelin is not always the best option.
Thank you in advance!

**Comment by janetst** [comment]
@Smotrov , sorry for the late reply, I am looking into this.

**Comment by janetst** [comment]
Hi, good news! We added a new tutorial that we hope will help solve this issue. See https://docs.aws.amazon.com/glue/latest/dg/dev-endpoint-tutorial-local-jupyter.html

Please open a new comment if there is an issue with the newly published tutorial.
