### ISSUE TITLE
Zeppelin notebook is not working after getting the endpoint via dev endpoints

### ISSUE THREAD

**Issue by hitesh1907nayyar** [awsdocs/aws-glue-developer-guide#39]
Hi, 

I am not able to open Zeppelin notebook when i create a notebook through dev endpoint. I have tried number of times still it always gives me " ec2-34-205-41-203.compute-1.amazonaws.com refused to connect"  ERR_CONNECTION_REFUSED 

The endpoint that i get from aws is not working.

https://ec2-34-205-41-203.compute-1.amazonaws.com:443

**Comment by janetst** [comment]
@hitesh1907nayyar , apologies for the very, very late reply. According to the docs "If you encounter a connection refused error, you might be using a development endpoint that is out of date. Try creating a new development endpoint and reconnecting. " Please let me know if that resolved your problem.

**Comment by Clete2** [comment]
@hitesh1907nayyar I have the same issue. Will be opening a case with AWS. However I have mine in a VPC in a private subnet.

**Comment by janetst** [comment]
@Clete2  - You might try out the new feature announced at re:Invent, VPC Reachability Analyzer, a network diagnostics tool that troubleshoots reachability between two endpoints in a VPC, or within multiple VPCs. You can read more about it at https://aws.amazon.com/blogs/aws/new-vpc-insights-analyzes-reachability-and-visibility-in-vpcs/

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the "awsdocs" org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
