### ISSUE TITLE
mapping a table from redshift in glue

### ISSUE THREAD

**Issue by AndresUrregoAngel** [awsdocs/aws-glue-developer-guide#4]
I want to reach out a table in my redshift cluster and bring it up to my AWS Glue environment to apply few transformations and queries on it. I try to apply the code below but the message I'm getting back in my log says: I create my code based in this official [example](https://docs.aws.amazon.com/glue/latest/dg/aws-glue-api-crawler-pyspark-extensions-dynamic-frame-reader.html#aws-glue-api-crawler-pyspark-extensions-dynamic-frame-reader-from_options)

> TypeError: unbound method from_options() must be called with
> DynamicFrameReader instance as first argument (got nothing instead)

 

Code in python 3.6:

```
    import sys
    from awsglue.transforms import *
    from awsglue.utils import getResolvedOptions
    from pyspark.context import SparkContext
    from awsglue.context import GlueContext
    from awsglue.dynamicframe import DynamicFrame  
    from awsglue.dynamicframe import DynamicFrameReader
    from pyspark.sql.functions import lit
    from awsglue.job import Job
    import psycopg2
    from sqlalchemy import create_engine
    
    table = DynamicFrameReader.from_options( connection_type="redshift", connection_options = 
        {"url": "jdbc:redshift://cluster.xxxxx.us-west-1.redshift.amazonaws.com:5439/db",
        "user": "xx",
        "password": "xx",
        "dbtable": "table",
        "redshiftTmpDir": "s3://aws-glue-temporary/"},format="csv", format_options={"separator":",","withHeader":"false"}, 
        transformation_ctx="table" )
    
    dfred = table.toDF().createOrReplaceTempView("table_df")
    
    job.commit()
```

I tried with a python library psycopg2 but :

> Traceback (most recent call last): File
> "script_2018-04-26-16-26-47.py", line 10, in <module> import psycopg2
> ImportError: No module named psycopg2 End of LogType:stdout

**Comment by ebattalio** [comment]
Hi, is this still an issue? If so, you could try posting the question to the AWS Glue forum at https://forums.aws.amazon.com/forum.jspa?forumID=262.

Thanks,
Eric
