### ISSUE TITLE
Update aws-glue-api-catalog-connnections.md 

### ISSUE THREAD

**Issue by BharatKJain** [awsdocs/aws-glue-developer-guide#46]
Here's the issue i was dealing with [link](https://stackoverflow.com/questions/56240778/aws-glue-unable-to-connect-to-mysql?rq=1), and then i had to create a VPC endpoint to resolve the issue.
The documentation doesn't mention anything related to VPC endpoint in glue connections.

Also version 8 of mysql is still not working with AWS Glue, so you might need to add an ISSUES heading and under it please mention that version 8 of mysql is not supported.

**Comment by janetst** [comment]
I am looking into this.

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the "awsdocs" org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
