### ISSUE TITLE
Update aws-glue-programming-python-libraries.md

### ISSUE THREAD

**Issue by BharatKJain** [awsdocs/aws-glue-developer-guide#47]
Pandas is supported by AWS Glue in python shell jobs now, please update this on [aws website](https://docs.aws.amazon.com/glue/latest/dg/add-job-python.html) as well as in the .md file(mentioned in heading of issue)

**Comment by janetst** [comment]
The documentation was updated at https://github.com/awsdocs/aws-glue-developer-guide/blob/master/doc_source/add-job-python.md#python-shell-supported-library , but the referenced file has not yet been updated.

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
