### ISSUE TITLE
Glue 2.0 docs update

### ISSUE THREAD

**Issue by aleksandersumowski** [awsdocs/aws-glue-developer-guide#48]
Now that Glue 2.0 is GA, could we have update of the documentation here?

**Comment by rubyumeshc** [comment]
thanks aleksandersumowski@
glue2.0 docs are available on aws public docs on below link
https://docs.aws.amazon.com/glue/latest/dg/reduced-start-times-spark-etl-jobs.html

guide here might be updated in time

**Comment by janetst** [comment]
Hi @aleksandersumowski , we are working on getting the developer guide refreshed on Github.

**Comment by janetst** [comment]
Glue doc on Github has been refreshed. See https://github.com/awsdocs/aws-glue-developer-guide/blob/master/doc_source/reduced-start-times-spark-etl-jobs.md
