### ISSUE TITLE
Update to Glue Job Bookmarks page

### ISSUE THREAD

**Issue by amadav** [awsdocs/aws-glue-developer-guide#59]
Hi,

I believe https://github.com/awsdocs/aws-glue-developer-guide/blob/master/doc_source/monitor-continuations.md still accounts for S3's eventual consistency. If I am not mistaken, S3 now provides strong read-after-write consistency and hence the solution (even if it still maintains an internal implementation for eventual consistency) should not mention that in the public documentation?

Not sure if I am missing something here :)

**Comment by janetst** [comment]
We will look into this.

**Comment by janetst** [comment]
Hi, this comment was removed in the latest doc update.
