### ISSUE TITLE
How to update only some parameters or properties of Glue Job via AWS CLI

### ISSUE THREAD

**Issue by sarmientoj24** [awsdocs/aws-glue-developer-guide#60]
I am currently implementing CI/CD pipeline of updating a Glue Job when new updates are pushed on Gitlab. This is done via AWS CLI script like this

```
aws glue update-job --job-name "$job" --job-update \
          "Role=AWSGlueServiceRole-dev,Command={Name=glueetl,ScriptLocation=s3://$S3_BUCKET/$S3_JOBS_SCRIPT_KEY/job_name.py}" \
          --region us-east-1
```

My problem is that it resets other parameters that are not included here.

**Comment by janetst** [comment]
Can you use the get-job command to first retrieve the settings for the job, then modify the results to change the desired parameter?  See https://docs.aws.amazon.com/cli/latest/reference/glue/get-job.html
