### ISSUE TITLE
DynamicFrame.resolveChoice method parameters out of date

### ISSUE THREAD

**Issue by ellisonc** [awsdocs/aws-glue-developer-guide#65]
The docs say: resolveChoice(specs = None, option="", transformation_ctx="", info="", stageThreshold=0, totalThreshold=0)
The code uses: resolveChoice(specs = None, choice="", transformation_ctx="", info="", stageThreshold=0, totalThreshold=0)

**Comment by janetst** [comment]
The HTML docs were updated a little while ago for this. https://docs.aws.amazon.com/glue/latest/dg/aws-glue-api-crawler-pyspark-extensions-dynamic-frame.html#aws-glue-api-crawler-pyspark-extensions-dynamic-frame-resolveChoice

See also:
https://docs.aws.amazon.com/glue/latest/dg/aws-glue-api-crawler-pyspark-transforms-ResolveChoice.html
https://docs.aws.amazon.com/glue/latest/dg/glue-etl-scala-apis-glue-dynamicframe-class.html#glue-etl-scala-apis-glue-dynamicframe-class-defs-resolveChoice

These Markdown files will be updated in the next refresh cycle.
