### ISSUE TITLE
Incomplete documentation

### ISSUE THREAD

**Issue by vaquarkhan** [awsdocs/aws-glue-developer-guide#85]
Incomplete documentation, talking a lot USA legislators dataset in all blogs and doc but no info how to glue job create different tables as mentions in example 

Your example start with assumption user has data and this is blocker , please update doc or removed example really confusing .
Example:
- https://aws.amazon.com/blogs/big-data/building-a-serverless-data-quality-and-analysis-framework-with-deequ-and-aws-glue/
- https://docs.aws.amazon.com/glue/latest/dg/aws-glue-programming-python-samples-legislators.html
- https://github.com/awsdocs/aws-glue-developer-guide/blob/master/doc_source/aws-glue-programming-python-samples-legislators.md
- https://github.com/aws-samples/aws-glue-samples/blob/master/examples/join_and_relationalize.md

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
