### ISSUE TITLE
Missing valid arguments from Glue Dev Endpoint

### ISSUE THREAD

**Issue by stevenayers** [awsdocs/aws-glue-developer-guide#88]
Valid keys and values for "Arguments" parameter are missing. https://github.com/awsdocs/aws-glue-developer-guide/blob/master/doc_source/aws-glue-api-dev-endpoint.md

The only one I could find was `GLUE_PYTHON_VERSION` which can either be `2` or `3`.

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
