### ISSUE TITLE
Set a workflow as failed from code

### ISSUE THREAD

**Issue by alecuba16** [awsdocs/aws-glue-developer-guide#90]
Hello!

I'm trying to set a workflow as failed with the boto3 api, but I'm unable to find any method to achieve that.

The motivation is despite the internal jobs are failed, the workflow is set as "completed" which makes NO sense, because its completed, yes, but because it failed.

I have to open every workflow on a very long list to check if it has failed.

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
