### ISSUE TITLE
Update table from jdbc connection

### ISSUE THREAD

**Issue by kellycastrof** [awsdocs/aws-glue-developer-guide#91]
I need to update some records from a table of JDBC connection on AWS glue, I saw some documentation of how to do it with catalogs, but not with JDBC.
Is there a way to do that?

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
