### ISSUE TITLE
FindMatches times out randomly

### ISSUE THREAD

**Issue by dustinadams999** [awsdocs/aws-glue-developer-guide#92]
I have a Glue ETL Job that gives a timeout error when trying to access the awsglueml.transforms.FindMatches library seemingly randomly. The error given on the glue dashboard is:

An error occurred while calling z:com.amazonaws.services.glue.ml.FindMatches.apply. The target server failed to respond

Basically if I try to run this Glue ETL job late at night, it most of the time succeeds. But if I try to run this ETL Job in the middle of the day, it fails with this error. Sometimes just retrying it enough times causes it to succeed, but this doesn't seem like a good solution.

The Glue ETL job was setup using the option "A proposed script generated by AWS Glue"

The line of code that this is timing out on is a line that was provided by glue when I created this job:

```
from awsglueml.transforms import FindMatches
...
findmatches2 = FindMatches.apply(frame = datasource0, transformId = "<redacted>", computeMatchConfidenceScores = True, transformation_ctx = "findmatches2")
```

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
