### ISSUE TITLE
--extra-jars - artifactory path instead of s3 location

### ISSUE THREAD

**Issue by ngarg-panw** [awsdocs/aws-glue-developer-guide#93]
Hi,

In my glue job, I am using certain java library jars from our repository. Right now I am specifying the s3 location.
But was wondering if it's possible to provide an artifact repository location instead?

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
