### ISSUE TITLE
Python modules already provided  needs an update for  Glue 4.0

### ISSUE THREAD

**Issue by quixoticmonk** [awsdocs/aws-glue-developer-guide#97]
The reference for python modules provided with Glue needs to be updated to 4.0

- Documentation : [aws-glue-programming-python-libraries.md](https://github.com/awsdocs/aws-glue-developer-guide/blob/master/doc_source/aws-glue-programming-python-libraries.md)

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
