### ISSUE TITLE
"dependency conflicts" when run a python shell job which is running from Glue console

### ISSUE THREAD

**Issue by luyanzheng** [awsdocs/aws-glue-developer-guide#99]
When I run a python shell job from the Glue console, I got the warning and error below. could you please help me to address the issue? Thanks
WARNING: The directory '/.cache/pip' or its parent directory is not owned or is not writable by the current user. The cache has been disabled. Check the permissions and owner of that directory. If executing pip with sudo, you should use sudo's -H flag.
WARNING: The directory '/.cache/pip' or its parent directory is not owned or is not writable by the current user. The cache has been disabled. Check the permissions and owner of that directory. If executing pip with sudo, you should use sudo's -H flag.
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
awscli 1.23.5 requires botocore==1.25.5, but you have botocore 1.24.21 which is incompatible.

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
